name: 'Sync with Upstream'

on:
  schedule:
    - cron:  '0 6 * * *'
    # scheduled at 06:00 everyday
  workflow_dispatch: {}

jobs:
  sync-with-upstream-main:
    runs-on: ubuntu-latest
    name: Sync with upstream main
    steps:
    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      with:
<<<<<<< Updated upstream
        persist-credentials: false

    - name: "Run analysis"
      uses: ossf/scorecard-action@62b2cac7ed8198b15735ed49ab1e5cf35480ba46  # v2.4.0
      with:
        results_file: results.sarif
        results_format: sarif
        publish_results: true

    - name: "Upload artifact"
      uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a  # v4.3.6
      with:
        name: SARIF file
        path: results.sarif
        retention-days: 5

    - name: "Upload to code-scanning"
      uses: github/codeql-action/upload-sarif@2c779ab0d087cd7fe7b826087247c2c81f27bfa6  # v3.26.5
      with:
        sarif_file: results.sarif
=======
        fetch-depth: 0
    - name: Sync upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
      with:
        target_sync_branch: main
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_sync_branch: main
        upstream_sync_repo: envoyproxy/go-control-plane
        test_mode: true
    - name: New commits found
      if: steps.sync.outputs.has_new_commits == 'true'
      run: echo "New commits were found to sync."
    
    - name: No new commits
      if: steps.sync.outputs.has_new_commits == 'false'
      run: echo "There were no new commits."
      
    - name: Show value of 'has_new_commits'
      run: echo ${{ steps.sync.outputs.has_new_commits }}
>>>>>>> Stashed changes
